<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Movies.Core\Movies.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Data\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="OllamaSharp" Version="5.4.11" />
      <PackageReference Include="Porter2StemmerStandard" Version="1.1.0" />
    </ItemGroup>
</Project>
