<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Movies.Core\Movies.Core.csproj" />
      <ProjectReference Include="..\Movies.Persistence\Movies.Persistence.csproj" />
      <ProjectReference Include="..\Movies.Search\Movies.Search.csproj" />
    </ItemGroup>

</Project>
