// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Persistence.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Movies.Migrations.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20251124214308_MovieEmbeddingsAdded")]
    partial class MovieEmbeddingsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Movies.Core.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CastMembers")
                        .HasColumnType("jsonb")
                        .HasColumnName("cast");

                    b.Property<string>("CrewMembers")
                        .HasColumnType("jsonb")
                        .HasColumnName("crew");

                    b.Property<string>("Genres")
                        .HasColumnType("jsonb")
                        .HasColumnName("genres");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .HasColumnType("jsonb")
                        .HasColumnName("keywords");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<double>("Popularity")
                        .HasColumnType("double precision");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TagLine")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("VoteAverage")
                        .HasColumnType("real");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Movies.Core.Entities.MovieEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(384)");

                    b.HasKey("Id");

                    b.ToTable("MovieEmbedding");
                });

            modelBuilder.Entity("Movies.Core.Entities.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TermText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TermType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TermText")
                        .HasDatabaseName("IX_Terms_TermText");

                    b.HasIndex("TermType")
                        .HasDatabaseName("IX_Terms_TermType");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("Movies.Core.Entities.TermFieldMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("TermId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldType")
                        .HasDatabaseName("IX_TermFieldMap_FieldMap");

                    b.HasIndex("MovieId");

                    b.HasIndex("TermId");

                    b.ToTable("TermFieldMap");
                });

            modelBuilder.Entity("Movies.Core.Entities.TermIndex", b =>
                {
                    b.Property<int>("TermId")
                        .HasColumnType("integer");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<float>("TermFrequency")
                        .HasColumnType("real");

                    b.PrimitiveCollection<int[]>("TermPositions")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("TermId", "MovieId");

                    b.HasIndex("MovieId", "TermId")
                        .HasDatabaseName("IX_TermIndex_MovieTerm");

                    b.ToTable("TermIndex");
                });

            modelBuilder.Entity("Movies.Core.Entities.TermVector", b =>
                {
                    b.Property<int>("TermId")
                        .HasColumnType("integer");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("TermId", "MovieId");

                    b.HasIndex("MovieId", "TermId")
                        .HasDatabaseName("IX_TermVectors_MovieTerm");

                    b.ToTable("TermVectors");
                });

            modelBuilder.Entity("Movies.Core.Entities.Movie", b =>
                {
                    b.HasOne("Movies.Core.Entities.MovieEmbedding", "Embedding")
                        .WithOne("Movie")
                        .HasForeignKey("Movies.Core.Entities.Movie", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Embedding");
                });

            modelBuilder.Entity("Movies.Core.Entities.TermFieldMap", b =>
                {
                    b.HasOne("Movies.Core.Entities.Movie", "Movie")
                        .WithMany("FieldMaps")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Core.Entities.Term", "Term")
                        .WithMany("FieldMaps")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Movies.Core.Entities.TermIndex", b =>
                {
                    b.HasOne("Movies.Core.Entities.Movie", "Movie")
                        .WithMany("TermIndex")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Core.Entities.Term", "Term")
                        .WithMany("Index")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Movies.Core.Entities.TermVector", b =>
                {
                    b.HasOne("Movies.Core.Entities.Movie", "Movie")
                        .WithMany("TermVectors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Core.Entities.Term", "Term")
                        .WithMany("Vectors")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Movies.Core.Entities.Movie", b =>
                {
                    b.Navigation("FieldMaps");

                    b.Navigation("TermIndex");

                    b.Navigation("TermVectors");
                });

            modelBuilder.Entity("Movies.Core.Entities.MovieEmbedding", b =>
                {
                    b.Navigation("Movie")
                        .IsRequired();
                });

            modelBuilder.Entity("Movies.Core.Entities.Term", b =>
                {
                    b.Navigation("FieldMaps");

                    b.Navigation("Index");

                    b.Navigation("Vectors");
                });
#pragma warning restore 612, 618
        }
    }
}
