// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Persistence.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movies.Migrations.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250814084001_MovieUpdated")]
    partial class MovieUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Movies.Core.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CastMembers")
                        .HasColumnType("jsonb")
                        .HasColumnName("cast");

                    b.Property<string>("CrewMembers")
                        .HasColumnType("jsonb")
                        .HasColumnName("crew");

                    b.Property<string>("Genres")
                        .HasColumnType("jsonb")
                        .HasColumnName("genres");

                    b.Property<string>("ImdbId")
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .HasColumnType("jsonb")
                        .HasColumnName("keywords");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<double>("Popularity")
                        .HasColumnType("double precision");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TagLine")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("VoteAverage")
                        .HasColumnType("real");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Movies.Core.Entities.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TermText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TermType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TermText");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("Movies.Core.Entities.TermIndex", b =>
                {
                    b.Property<int>("TermId")
                        .HasColumnType("integer");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<float>("TermFrequency")
                        .HasColumnType("real");

                    b.PrimitiveCollection<int[]>("TermPositions")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("TermId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("TermIndex");
                });

            modelBuilder.Entity("Movies.Core.Entities.TermVector", b =>
                {
                    b.Property<int>("TermId")
                        .HasColumnType("integer");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("TermId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("TermVectors");
                });

            modelBuilder.Entity("Movies.Core.Entities.TermIndex", b =>
                {
                    b.HasOne("Movies.Core.Entities.Movie", "Movie")
                        .WithMany("TermIndex")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Core.Entities.Term", "Term")
                        .WithMany("Index")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Movies.Core.Entities.TermVector", b =>
                {
                    b.HasOne("Movies.Core.Entities.Movie", "Movie")
                        .WithMany("TermVectors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Core.Entities.Term", "Term")
                        .WithMany("Vectors")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Movies.Core.Entities.Movie", b =>
                {
                    b.Navigation("TermIndex");

                    b.Navigation("TermVectors");
                });

            modelBuilder.Entity("Movies.Core.Entities.Term", b =>
                {
                    b.Navigation("Index");

                    b.Navigation("Vectors");
                });
#pragma warning restore 612, 618
        }
    }
}
